version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/paradknow
    command: >
      sh -c "python manage.py migrate &&
             gunicorn paradknow.wsgi:application --bind 0.0.0.0:8000"
